export const A_Level_EXAM_DATA = [
    // AQA
    { exam_board: "AQA", subject: "Accounting", level: "A-Level" },
    { exam_board: "AQA", subject: "Biology", level: "A-Level" },
    { exam_board: "AQA", subject: "Business", level: "A-Level" },
    { exam_board: "AQA", subject: "Chemistry", level: "A-Level" },
    { exam_board: "AQA", subject: "Computer Science", level: "A-Level" },
    { exam_board: "AQA", subject: "Economics", level: "A-Level" },
    { exam_board: "AQA", subject: "English Language", level: "A-Level" },
    { exam_board: "AQA", subject: "English Language & Literature", level: "A-Level" },
    { exam_board: "AQA", subject: "English Literature", level: "A-Level" },
    { exam_board: "AQA", subject: "French", level: "A-Level" },
    { exam_board: "AQA", subject: "Further Maths", level: "A-Level" },
    { exam_board: "AQA", subject: "Geography", level: "A-Level" },
    { exam_board: "AQA", subject: "German", level: "A-Level" },
    { exam_board: "AQA", subject: "History", level: "A-Level" },
    { exam_board: "AQA", subject: "Maths", level: "A-Level" },
    { exam_board: "AQA", subject: "Physics", level: "A-Level" },
    { exam_board: "AQA", subject: "Politics", level: "A-Level" },
    { exam_board: "AQA", subject: "Psychology", level: "A-Level" },
    { exam_board: "AQA", subject: "Religious Studies", level: "A-Level" },
    { exam_board: "AQA", subject: "Sociology", level: "A-Level" },
    { exam_board: "AQA", subject: "Spanish", level: "A-Level" },

    // Cambridge (CIE)
    { exam_board: "Cambridge (CIE)", subject: "Accounting", level: "A-Level" },
    { exam_board: "Cambridge (CIE)", subject: "Biology", level: "A-Level" },
    { exam_board: "Cambridge (CIE)", subject: "Business", level: "A-Level" },
    { exam_board: "Cambridge (CIE)", subject: "Chemistry", level: "A-Level" },
    { exam_board: "Cambridge (CIE)", subject: "Computer Science", level: "A-Level" },
    { exam_board: "Cambridge (CIE)", subject: "Economics", level: "A-Level" },
    { exam_board: "Cambridge (CIE)", subject: "English Language", level: "A-Level" },
    { exam_board: "Cambridge (CIE)", subject: "English Literature", level: "A-Level" },
    { exam_board: "Cambridge (CIE)", subject: "French", level: "A-Level" },
    { exam_board: "Cambridge (CIE)", subject: "Further Maths", level: "A-Level" },
    { exam_board: "Cambridge (CIE)", subject: "Geography", level: "A-Level" },
    { exam_board: "Cambridge (CIE)", subject: "German", level: "A-Level" },
    { exam_board: "Cambridge (CIE)", subject: "History", level: "A-Level" },
    { exam_board: "Cambridge (CIE)", subject: "Maths", level: "A-Level" },
    { exam_board: "Cambridge (CIE)", subject: "Physics", level: "A-Level" },
    { exam_board: "Cambridge (CIE)", subject: "Psychology", level: "A-Level" },
    { exam_board: "Cambridge (CIE)", subject: "Religious Studies", level: "A-Level" },
    { exam_board: "Cambridge (CIE)", subject: "Sociology", level: "A-Level" },
    { exam_board: "Cambridge (CIE)", subject: "Spanish", level: "A-Level" },

    // CCEA
    { exam_board: "CCEA", subject: "Biology", level: "A-Level" },
    { exam_board: "CCEA", subject: "Further Maths", level: "A-Level" },
    { exam_board: "CCEA", subject: "Maths", level: "A-Level" },

    // Edexcel
    { exam_board: "Edexcel", subject: "Biology", level: "A-Level" },
    { exam_board: "Edexcel", subject: "Business", level: "A-Level" },
    { exam_board: "Edexcel", subject: "Chemistry", level: "A-Level" },
    { exam_board: "Edexcel", subject: "Economics", level: "A-Level" },
    { exam_board: "Edexcel", subject: "English Language", level: "A-Level" },
    { exam_board: "Edexcel", subject: "English Literature", level: "A-Level" },
    { exam_board: "Edexcel", subject: "French", level: "A-Level" },
    { exam_board: "Edexcel", subject: "Further Maths", level: "A-Level" },
    { exam_board: "Edexcel", subject: "Geography", level: "A-Level" },
    { exam_board: "Edexcel", subject: "German", level: "A-Level" },
    { exam_board: "Edexcel", subject: "History", level: "A-Level" },
    { exam_board: "Edexcel", subject: "Maths", level: "A-Level" },
    { exam_board: "Edexcel", subject: "Physics", level: "A-Level" },
    { exam_board: "Edexcel", subject: "Politics", level: "A-Level" },
    { exam_board: "Edexcel", subject: "Psychology", level: "A-Level" },
    { exam_board: "Edexcel", subject: "Religious Studies", level: "A-Level" },
    { exam_board: "Edexcel", subject: "Spanish", level: "A-Level" },

    // Edexcel International
    { exam_board: "Edexcel International", subject: "Accounting", level: "A-Level" },
    { exam_board: "Edexcel International", subject: "Biology", level: "A-Level" },
    { exam_board: "Edexcel International", subject: "Chemistry", level: "A-Level" },
    { exam_board: "Edexcel International", subject: "Computer Science", level: "A-Level" },
    { exam_board: "Edexcel International", subject: "Economics", level: "A-Level" },
    { exam_board: "Edexcel International", subject: "English Language", level: "A-Level" },
    { exam_board: "Edexcel International", subject: "English Literature", level: "A-Level" },
    { exam_board: "Edexcel International", subject: "French", level: "A-Level" },
    { exam_board: "Edexcel International", subject: "Further Maths", level: "A-Level" },
    { exam_board: "Edexcel International", subject: "Geography", level: "A-Level" },
    { exam_board: "Edexcel International", subject: "German", level: "A-Level" },
    { exam_board: "Edexcel International", subject: "History", level: "A-Level" },
    { exam_board: "Edexcel International", subject: "Maths", level: "A-Level" },
    { exam_board: "Edexcel International", subject: "Physics", level: "A-Level" },
    { exam_board: "Edexcel International", subject: "Psychology", level: "A-Level" },
    { exam_board: "Edexcel International", subject: "Spanish", level: "A-Level" },

    // OCR
    { exam_board: "OCR", subject: "Biology", level: "A-Level" },
    { exam_board: "OCR", subject: "Business", level: "A-Level" },
    { exam_board: "OCR", subject: "Chemistry", level: "A-Level" },
    { exam_board: "OCR", subject: "Computer Science", level: "A-Level" },
    { exam_board: "OCR", subject: "Economics", level: "A-Level" },
    { exam_board: "OCR", subject: "English Language", level: "A-Level" },
    { exam_board: "OCR", subject: "English Literature", level: "A-Level" },
    { exam_board: "OCR", subject: "Further Maths", level: "A-Level" },
    { exam_board: "OCR", subject: "Geography", level: "A-Level" },
    { exam_board: "OCR", subject: "History", level: "A-Level" },
    { exam_board: "OCR", subject: "Maths", level: "A-Level" },
    { exam_board: "OCR", subject: "Physics", level: "A-Level" },
    { exam_board: "OCR", subject: "Psychology", level: "A-Level" },
    { exam_board: "OCR", subject: "Religious Studies", level: "A-Level" },
    { exam_board: "OCR", subject: "Sociology", level: "A-Level" },

    // Oxford AQA
    { exam_board: "Oxford AQA", subject: "Biology", level: "A-Level" },
    { exam_board: "Oxford AQA", subject: "Business", level: "A-Level" },
    { exam_board: "Oxford AQA", subject: "Chemistry", level: "A-Level" },
    { exam_board: "Oxford AQA", subject: "Economics", level: "A-Level" },
    { exam_board: "Oxford AQA", subject: "English Language", level: "A-Level" },
    { exam_board: "Oxford AQA", subject: "English Literature", level: "A-Level" },
    { exam_board: "Oxford AQA", subject: "Further Maths", level: "A-Level" },
    { exam_board: "Oxford AQA", subject: "Geography", level: "A-Level" },
    { exam_board: "Oxford AQA", subject: "Maths", level: "A-Level" },
    { exam_board: "Oxford AQA", subject: "Physics", level: "A-Level" },
    { exam_board: "Oxford AQA", subject: "Psychology", level: "A-Level" },

    // WJEC
    { exam_board: "WJEC", subject: "English Language", level: "A-Level" },
    { exam_board: "WJEC", subject: "English Language & Literature", level: "A-Level" },
    { exam_board: "WJEC", subject: "French", level: "A-Level" },
    { exam_board: "WJEC", subject: "German", level: "A-Level" },
    { exam_board: "WJEC", subject: "Physics", level: "A-Level" },
    { exam_board: "WJEC", subject: "Politics", level: "A-Level" },
    { exam_board: "WJEC", subject: "Psychology", level: "A-Level" },
    { exam_board: "WJEC", subject: "Religious Studies", level: "A-Level" },
    { exam_board: "WJEC", subject: "Spanish", level: "A-Level" },

    // WJEC Eduqas
    { exam_board: "WJEC Eduqas", subject: "Chemistry", level: "A-Level" },
    { exam_board: "WJEC Eduqas", subject: "Computer Science", level: "A-Level" },
    { exam_board: "WJEC Eduqas", subject: "French", level: "A-Level" },
    { exam_board: "WJEC Eduqas", subject: "Geography", level: "A-Level" },
    { exam_board: "WJEC Eduqas", subject: "German", level: "A-Level" },
    { exam_board: "WJEC Eduqas", subject: "Psychology", level: "A-Level" },
    { exam_board: "WJEC Eduqas", subject: "Spanish", level: "A-Level" },
];