export const EXAM_DATA = [
    { "exam_board": "AQA", "subject": "English Language", "tier": "Foundation" },
    { "exam_board": "AQA", "subject": "English Language", "tier": "Higher" },
    { "exam_board": "AQA", "subject": "English Literature", "tier": "Untiered" },
    { "exam_board": "AQA", "subject": "Mathematics", "tier": "Foundation" },
    { "exam_board": "AQA", "subject": "Mathematics", "tier": "Higher" },
    { "exam_board": "AQA", "subject": "Combined Science", "tier": "Foundation" },
    { "exam_board": "AQA", "subject": "Combined Science", "tier": "Higher" },
    { "exam_board": "AQA", "subject": "Biology", "tier": "Foundation" },
    { "exam_board": "AQA", "subject": "Biology", "tier": "Higher" },
    { "exam_board": "AQA", "subject": "Chemistry", "tier": "Foundation" },
    { "exam_board": "AQA", "subject": "Chemistry", "tier": "Higher" },
    { "exam_board": "AQA", "subject": "Physics", "tier": "Foundation" },
    { "exam_board": "AQA", "subject": "Physics", "tier": "Higher" },
    { "exam_board": "AQA", "subject": "History", "tier": "Untiered" },
    { "exam_board": "AQA", "subject": "Geography", "tier": "Untiered" },
    { "exam_board": "AQA", "subject": "Religious Studies", "tier": "Untiered" },
    { "exam_board": "AQA", "subject": "French", "tier": "Untiered" },
    { "exam_board": "AQA", "subject": "Spanish", "tier": "Untiered" },
    { "exam_board": "AQA", "subject": "German", "tier": "Untiered" },
    { "exam_board": "AQA", "subject": "Italian", "tier": "Untiered" },
    { "exam_board": "AQA", "subject": "Polish", "tier": "Untiered" },
    { "exam_board": "AQA", "subject": "Urdu", "tier": "Untiered" },
    { "exam_board": "AQA", "subject": "Arabic", "tier": "Untiered" },
    { "exam_board": "AQA", "subject": "Bengali", "tier": "Untiered" },
    { "exam_board": "AQA", "subject": "Panjabi", "tier": "Untiered" },
    { "exam_board": "AQA", "subject": "Gujarati", "tier": "Untiered" },
    { "exam_board": "AQA", "subject": "Psychology", "tier": "Untiered" },
    { "exam_board": "AQA", "subject": "Sociology", "tier": "Untiered" },
    { "exam_board": "AQA", "subject": "Citizenship Studies", "tier": "Untiered" },
    { "exam_board": "AQA", "subject": "Computer Science", "tier": "Untiered" },
    { "exam_board": "AQA", "subject": "Business", "tier": "Untiered" },
    { "exam_board": "AQA", "subject": "Economics", "tier": "Untiered" },
    { "exam_board": "AQA", "subject": "Design and Technology", "tier": "Untiered" },
    { "exam_board": "AQA", "subject": "Food Preparation and Nutrition", "tier": "Untiered" },
    { "exam_board": "AQA", "subject": "Art and Design", "tier": "Untiered" },
    { "exam_board": "AQA", "subject": "Drama", "tier": "Untiered" },
    { "exam_board": "AQA", "subject": "Music", "tier": "Untiered" },
    { "exam_board": "AQA", "subject": "Physical Education", "tier": "Untiered" },
    { "exam_board": "AQA", "subject": "Media Studies", "tier": "Untiered" },

    // Edexcel
    { "exam_board": "Edexcel", "subject": "English Language", "tier": "Foundation" },
    { "exam_board": "Edexcel", "subject": "English Language", "tier": "Higher" },
    { "exam_board": "Edexcel", "subject": "English Literature", "tier": "Untiered" },
    { "exam_board": "Edexcel", "subject": "Mathematics", "tier": "Foundation" },
    { "exam_board": "Edexcel", "subject": "Mathematics", "tier": "Higher" },
    { "exam_board": "Edexcel", "subject": "Combined Science", "tier": "Foundation" },
    { "exam_board": "Edexcel", "subject": "Combined Science", "tier": "Higher" },
    { "exam_board": "Edexcel", "subject": "Biology", "tier": "Foundation" },
    { "exam_board": "Edexcel", "subject": "Biology", "tier": "Higher" },
    { "exam_board": "Edexcel", "subject": "Chemistry", "tier": "Foundation" },
    { "exam_board": "Edexcel", "subject": "Chemistry", "tier": "Higher" },
    { "exam_board": "Edexcel", "subject": "Physics", "tier": "Foundation" },
    { "exam_board": "Edexcel", "subject": "Physics", "tier": "Higher" },
    { "exam_board": "Edexcel", "subject": "History", "tier": "Untiered" },
    { "exam_board": "Edexcel", "subject": "Geography A", "tier": "Untiered" },
    { "exam_board": "Edexcel", "subject": "Geography B", "tier": "Untiered" },
    { "exam_board": "Edexcel", "subject": "Religious Studies", "tier": "Untiered" },
    { "exam_board": "Edexcel", "subject": "French", "tier": "Untiered" },
    { "exam_board": "Edexcel", "subject": "Spanish", "tier": "Untiered" },
    { "exam_board": "Edexcel", "subject": "German", "tier": "Untiered" },
    { "exam_board": "Edexcel", "subject": "Italian", "tier": "Untiered" },
    { "exam_board": "Edexcel", "subject": "Chinese", "tier": "Untiered" },
    { "exam_board": "Edexcel", "subject": "Arabic", "tier": "Untiered" },
    { "exam_board": "Edexcel", "subject": "Urdu", "tier": "Untiered" },
    { "exam_board": "Edexcel", "subject": "Gujarati", "tier": "Untiered" },
    { "exam_board": "Edexcel", "subject": "Psychology", "tier": "Untiered" },
    { "exam_board": "Edexcel", "subject": "Sociology", "tier": "Untiered" },
    { "exam_board": "Edexcel", "subject": "Citizenship Studies", "tier": "Untiered" },
    { "exam_board": "Edexcel", "subject": "Computer Science", "tier": "Untiered" },
    { "exam_board": "Edexcel", "subject": "Business", "tier": "Untiered" },
    { "exam_board": "Edexcel", "subject": "Economics", "tier": "Untiered" },
    { "exam_board": "Edexcel", "subject": "Design and Technology", "tier": "Untiered" },
    { "exam_board": "Edexcel", "subject": "Food Preparation and Nutrition", "tier": "Untiered" },
    { "exam_board": "Edexcel", "subject": "Art and Design", "tier": "Untiered" },
    { "exam_board": "Edexcel", "subject": "Drama", "tier": "Untiered" },
    { "exam_board": "Edexcel", "subject": "Music", "tier": "Untiered" },
    { "exam_board": "Edexcel", "subject": "Physical Education", "tier": "Untiered" },
    { "exam_board": "Edexcel", "subject": "Media Studies", "tier": "Untiered" },
    { "exam_board": "Edexcel", "subject": "Statistics", "tier": "Untiered" },

    // OCR
    { "exam_board": "OCR", "subject": "English Language", "tier": "Foundation" },
    { "exam_board": "OCR", "subject": "English Language", "tier": "Higher" },
    { "exam_board": "OCR", "subject": "English Literature", "tier": "Untiered" },
    { "exam_board": "OCR", "subject": "Mathematics", "tier": "Foundation" },
    { "exam_board": "OCR", "subject": "Mathematics", "tier": "Higher" },
    { "exam_board": "OCR", "subject": "Combined Science", "tier": "Untiered" },
    { "exam_board": "OCR", "subject": "Biology", "tier": "Foundation" },
    { "exam_board": "OCR", "subject": "Biology", "tier": "Higher" },
    { "exam_board": "OCR", "subject": "Chemistry", "tier": "Foundation" },
    { "exam_board": "OCR", "subject": "Chemistry", "tier": "Higher" },
    { "exam_board": "OCR", "subject": "Physics", "tier": "Foundation" },
    { "exam_board": "OCR", "subject": "Physics", "tier": "Higher" },
    { "exam_board": "OCR", "subject": "History", "tier": "Untiered" },
    { "exam_board": "OCR", "subject": "Geography", "tier": "Untiered" },
    { "exam_board": "OCR", "subject": "Religious Studies", "tier": "Untiered" },
    { "exam_board": "OCR", "subject": "French", "tier": "Untiered" },
    { "exam_board": "OCR", "subject": "Spanish", "tier": "Untiered" },
    { "exam_board": "OCR", "subject": "German", "tier": "Untiered" },
    { "exam_board": "OCR", "subject": "Italian", "tier": "Untiered" },
    { "exam_board": "OCR", "subject": "Psychology", "tier": "Untiered" },
    { "exam_board": "OCR", "subject": "Sociology", "tier": "Untiered" },
    { "exam_board": "OCR", "subject": "Citizenship Studies", "tier": "Untiered" },
    { "exam_board": "OCR", "subject": "Computer Science", "tier": "Untiered" },
    { "exam_board": "OCR", "subject": "Business", "tier": "Untiered" },
    { "exam_board": "OCR", "subject": "Economics", "tier": "Untiered" },
    { "exam_board": "OCR", "subject": "Design and Technology", "tier": "Untiered" },
    { "exam_board": "OCR", "subject": "Food Preparation and Nutrition", "tier": "Untiered" },
    { "exam_board": "OCR", "subject": "Art and Design", "tier": "Untiered" },
    { "exam_board": "OCR", "subject": "Drama", "tier": "Untiered" },
    { "exam_board": "OCR", "subject": "Music", "tier": "Untiered" },
    { "exam_board": "OCR", "subject": "Physical Education", "tier": "Untiered" },
    { "exam_board": "OCR", "subject": "Media Studies", "tier": "Untiered" },
    { "exam_board": "OCR", "subject": "Classical Civilisation", "tier": "Untiered" },
    { "exam_board": "OCR", "subject": "Latin", "tier": "Untiered" }
];